name: "GitHub Markdown Linter"

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  lint:
    name: Run all workflow linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: p6m7g8-actions/checkout@main

      - name: Run P6 Markdown Linter
        uses: ./
